# This Docker Compose file can be used to quickly bootup Dgraph Zero
# and Alpha in different Docker containers.

# It mounts /tmp/data on the host machine to /dgraph within the
# container. You can change /tmp/data to a more appropriate location.
# Run `docker-compose up` to start Dgraph.
# NOTE: whitelisting is set to private address ranges, this is ONLY for a local setup
#       please change it accordingly for your production setup
#       more here https://dgraph.io/docs/deploy/dgraph-administration/#whitelisting-admin-operations

version: "3.2"
services:
  zero:
    image: philoupy/dgraph-aarch64:latest
    volumes:
      - data-volume:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  alpha:
    image: philoupy/dgraph-aarch64:latest
    volumes:
      - data-volume:/dgraph
    ports:
      - 8000:8000
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command:
      dgraph alpha --my=alpha:7080 --zero=zero:5080 --security whitelist=0.0.0.0/0
      #  --lambda="url=""; num=0; port=20000; restart-after=30s;"

volumes:
  data-volume:
